name: health
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  google_sign_in: ^6.2.1
  http: ^1.2.2
  image_picker: ^1.0.7
  pedometer: ^4.2.0
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.4
  cupertino_icons: ^1.0.8
  image: ^4.1.7
  flutter_blue_plus: ^1.34.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/social/
