// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuaohuV6vPBETNV_I_90iCKfBNDC0WlH0',
    appId: '1:248401716582:web:0f77c262e93707db2294a7',
    messagingSenderId: '248401716582',
    projectId: 'health-tracker-b63aa',
    authDomain: 'health-tracker-b63aa.firebaseapp.com',
    storageBucket: 'health-tracker-b63aa.firebasestorage.app',
    measurementId: 'G-E7Q7SS9V4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh-4w6MHTOzvq9dRy6g011gdd92Bpfw3M',
    appId: '1:248401716582:android:417f4015583a230b2294a7',
    messagingSenderId: '248401716582',
    projectId: 'health-tracker-b63aa',
    storageBucket: 'health-tracker-b63aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoV8uWE07W0OMJgZzcfdKyYWce3jdCEpo',
    appId: '1:248401716582:ios:6e420b4ac2d03b1c2294a7',
    messagingSenderId: '248401716582',
    projectId: 'health-tracker-b63aa',
    storageBucket: 'health-tracker-b63aa.firebasestorage.app',
    iosBundleId: 'com.example.health',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoV8uWE07W0OMJgZzcfdKyYWce3jdCEpo',
    appId: '1:248401716582:ios:6e420b4ac2d03b1c2294a7',
    messagingSenderId: '248401716582',
    projectId: 'health-tracker-b63aa',
    storageBucket: 'health-tracker-b63aa.firebasestorage.app',
    iosBundleId: 'com.example.health',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuaohuV6vPBETNV_I_90iCKfBNDC0WlH0',
    appId: '1:248401716582:web:c4be7cf08481ca7d2294a7',
    messagingSenderId: '248401716582',
    projectId: 'health-tracker-b63aa',
    authDomain: 'health-tracker-b63aa.firebaseapp.com',
    storageBucket: 'health-tracker-b63aa.firebasestorage.app',
    measurementId: 'G-1KWLLF8C02',
  );
}
